function print_statistics(results,simulations,p)

    %% Wealth Distribution
    
    fprintf('\nWEALTH DISTRIBUTION: \n')
    if p.Simulate == 1
        fprintf('   Mean wealth: %2.3f (Direct Computation), %2.3f (Simulation) \n',...
            results.mean_s,simulations.mean_s);
        fprintf('    Mean cash-on-hand: %2.3f (Direct Computation), %2.3f (Simulation) \n',...
            results.mean_x,simulations.mean_x);
        fprintf('    Fraction constrained: %2.3f (Direct Computation), %2.3f (Simulation) \n',...
            results.frac_constrained,simulations.frac_constrained);
    else
        fprintf('    Mean wealth: %2.3f (Direct Computation)\n',...
            results.mean_s);
        fprintf('    Mean cash-on-hand: %2.3f (Direct Computation)\n',...
            results.mean_x);
        fprintf(' Fraction constrained: %2.3f (Direct Computation)\n',...
            results.frac_constrained);
    end
    fprintf('    Fraction <5 percent mean lab inc: %2.3f\n',...
        results.frac_less5perc_labincome);
    fprintf('    10th percentile: %2.3f\n',...
        results.p10wealth);
    fprintf('    25th percentile: %2.3f\n',...
        results.p25wealth);
    fprintf('    50th percentile: %2.3f\n',...
        results.p50wealth);
    fprintf('    90th percentile: %2.3f\n',...
        results.p90wealth); 
    fprintf('    99th percentile: %2.3f\n',...
        results.p99wealth);
end