#!/bin/bash
# run sbatch files and clean up output and temp directories

mkdir -p ~/GitHub/Discrete_HA/Output
mkdir -p ~/GitHub/Discrete_HA/Temp

if ! [ -z "$(ls ~/GitHub/Discrete_HA/Output)" ]; then
  rm ~/GitHub/Discrete_HA/Output/*
fi

cd ~/GitHub/Discrete_HA/batch
array=$(ls *.sbatch)

for i in ${array[@]}
do
  sbatch "$i"
done
